## Documentation: http://docs.travis-ci.org/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
  - nightly

notifications:
  email: false

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: osx
  include:
    - stage: "Cross Package Testing"
      julia: 1.3
      env:
        PACKAGE=PowerSystems
      script:
        - cd $HOME
        - julia -e 'const PKG_FOLDER = ENV["TRAVIS_BUILD_DIR"]; using Pkg; Pkg.develop(PackageSpec(path=PKG_FOLDER))'
        - julia -e 'const PACKAGE = ENV["PACKAGE"]; using Pkg; Pkg.develop(PACKAGE); Pkg.instantiate(); Pkg.test(PACKAGE)'
      after_success: skip
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd())); Pkg.build()'
        - julia --project=docs --color=yes -e 'include("docs/make.jl")'
      after_success: skip
after_success: julia -e '
  using Pkg;
  Pkg.add("Coverage");
  using Coverage;
  Codecov.submit(process_folder());'
